### ISSUE TITLE
Create a new issue here like this one to get my attention.

### ISSUE THREAD

**Issue by ubuvoid** [Unofficial-Whisperplay-Fling-Helpline/wp#1]
eom

**Comment by ubuvoid** [comment]
Integrating with WhisperPlay (aka FlingSDK)? I'm sorry to hear that.

I helped implement this library in 2013-2016, and I'm here to save you some time so you don't have to spend as many sleepless nights decyphering the logs as I did. File a bug here and I'll do my best to point you in the right direction.

**Comment by krishna415741** [comment]
Hi we are not able to cast anything to fire tv. getting this error "The Input Description is null". please let me know how to fix this.

Thank you

**Comment by ubuvoid** [comment]
Can you collect and share error logs from the device? Also, can you clarify which platform you're using? (android, ios, fire os, etc)

Thanks!

**Comment by krishna415741** [comment]
Currently we are using in react native Native Module(Android). The Only error we are facing is Input Description is null when tried to fling content.

Thank you

**Comment by krishna415741** [comment]
"Unable to get external transport, channel factory is null, channel=null"
 getting this error while trying to fling content.

**Comment by krishna4157** [comment]
No Whisperplay XML, will not be hosting any services

2022-11-17 15:02:14.427 13605-13820/com.castapp D/HELLO WORLD888 :: [MediaPlayer.MediaInfo.Get, MediaPlayer.Display.Image, MediaPlayer.Play.Audio, MediaPlayer.Play.Video, MediaPlayer.Close, MediaPlayer.MetaData.MimeType, MediaPlayer.MetaData.Thumbnail, MediaPlayer.MetaData.Title, MediaPlayer.Subtitle.WebVTT, MediaControl.Play, MediaControl.Pause, MediaControl.Stop, MediaControl.Seek, MediaControl.Duration, MediaControl.Position, MediaControl.PlayState, MediaControl.PlayState.Subscribe]
2022-11-17 15:02:14.428 13605-13820/com.castapp D/HELLO WORLD888 :: naman's FireTVStick
2022-11-17 15:02:14.429 13605-16358/com.castapp D/WhisperLink: Connection - Connection Attempt #:0: Excluded transports :[]
2022-11-17 15:02:14.429 13605-16358/com.castapp D/WhisperLink: Connection - doConnectOnce, device=[device=null], service=Description(sid:amzn.reg, friendlyName:null, accessLevel:3, security:0, flags:0, version:1), protocol=null, channel=null; excluded=[]
2022-11-17 15:02:14.429 13605-16358/com.castapp D/WhisperLink: TTransportManager - Get transport for local device amzn.reg
2022-11-17 15:02:14.429 13605-16358/com.castapp D/WhisperLink: Connection - Returning a cache transport for amzn.reg
2022-11-17 15:02:14.429 13605-16358/com.castapp D/WhisperLink: Connection - calling Connection.close for device() [device=null]
2022-11-17 15:02:14.429 13605-16358/com.castapp D/PlayerDeviceImpl: callService.run() - connection=com.amazon.whisperlink.util.Connection@7f68dfb
2022-11-17 15:02:14.430 13605-16358/com.castapp D/WhisperLink: Connection - Connection Attempt #:0: Excluded transports :[]
2022-11-17 15:02:14.430 13605-16358/com.castapp D/WhisperLink: Connection - doConnectOnce, device=[device: local=false, uuid=D025D3547580E1F1A3149BDAA649352D, routes={inet=Route(ipv4:192.168.29.193, unsecurePort:36474, securePort:38380)}], service=Description(sid:amzn.thin.pl, friendlyName:null, accessLevel:0, security:0, flags:0, version:0), protocol=null, channel=null; excluded=[]
2022-11-17 15:02:14.430 13605-16358/com.castapp D/WhisperLink: Connection - Connection Attempt #:0: Excluded transports :[]
2022-11-17 15:02:14.430 13605-16358/com.castapp D/WhisperLink: Connection - doConnectOnce, device=[device=null], service=Description(sid:amzn.reg, friendlyName:null, accessLevel:3, security:0, flags:0, version:1), protocol=null, channel=null; excluded=[]
2022-11-17 15:02:14.430 13605-16358/com.castapp D/WhisperLink: TTransportManager - Get transport for local device amzn.reg
2022-11-17 15:02:14.430 13605-16358/com.castapp D/WhisperLink: Connection - Returning a cache transport for amzn.reg
2022-11-17 15:02:14.431 13605-16358/com.castapp D/WhisperLink: Connection - calling Connection.close for device() [device=null]
2022-11-17 15:02:14.431 13605-16358/com.castapp D/WhisperLink: TTransportManager - Get transport for remote device amzn.thin.pl; channel:null
2022-11-17 15:02:14.431 13605-16358/com.castapp D/WhisperLink: TTransportManager - Getting external transport for channel:inet: Channel connected? :false: ext channel :com.amazon.whisperlink.port.android.transport.TExternalSocketFactory@a3de1f6
2022-11-17 15:02:14.431 13605-16358/com.castapp E/WhisperLink: TTransportManager - Unable to get external transport, channel factory is null, channel=null
2022-11-17 15:02:14.431 13605-16358/com.castapp D/WhisperLink: Connection - Exception in connection:null
com.amazon.whisperlink.exception.WPTException
at com.amazon.whisperlink.util.Connection.doConnectOnce(Connection.java:679)
at com.amazon.whisperlink.util.Connection.doConnect(Connection.java:587)
at com.amazon.whisperlink.util.Connection.doConnect(Connection.java:537)
at com.amazon.whisperlink.util.Connection.connect(Connection.java:380)
at com.amazon.whisperplay.fling.media.controller.impl.PlayerDeviceImpl$23.call(PlayerDeviceImpl.java:457)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
2022-11-17 15:02:14.431 13605-16358/com.castapp W/WhisperLink: Connection - No route to service :Description(sid:amzn.thin.pl, friendlyName:null, accessLevel:0, security:0, flags:0, version:0): on device :[device: local=false, uuid=D025D3547580E1F1A3149BDAA649352D]
2022-11-17 15:02:14.432 13605-16358/com.castapp W/WhisperLink: Connection - Exception in connection. Exception code :1 :class com.amazon.whisperlink.exception.WPTException :com.amazon.whisperlink.exception.WPTException
2022-11-17 15:02:14.432 13605-16358/com.castapp D/WhisperLink: Connection - calling Connection.close for device() [device: local=false, uuid=D025D3547580E1F1A3149BDAA649352D, routes={inet=Route(ipv4:192.168.29.193, unsecurePort:36474, securePort:38380)}]
2022-11-17 15:02:14.432 13605-16358/com.castapp E/PlayerDeviceImpl: Exception:
com.amazon.whisperlink.exception.WPTException: com.amazon.whisperlink.exception.WPTException
at com.amazon.whisperlink.util.Connection.throwIfNetworkError(Connection.java:804)
at com.amazon.whisperlink.util.Connection.doConnectOnce(Connection.java:725)
at com.amazon.whisperlink.util.Connection.doConnect(Connection.java:587)
at com.amazon.whisperlink.util.Connection.doConnect(Connection.java:537)
at com.amazon.whisperlink.util.Connection.connect(Connection.java:380)
at com.amazon.whisperplay.fling.media.controller.impl.PlayerDeviceImpl$23.call(PlayerDeviceImpl.java:457)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Caused by: com.amazon.whisperlink.exception.WPTException
at com.amazon.whisperlink.util.Connection.doConnectOnce(Connection.java:679)
at com.amazon.whisperlink.util.Connection.doConnect(Connection.java:587) 
at com.amazon.whisperlink.util.Connection.doConnect(Connection.java:537) 
at com.amazon.whisperlink.util.Connection.connect(Connection.java:380) 
at com.amazon.whisperplay.fling.media.controller.impl.PlayerDeviceImpl$23.call(PlayerDeviceImpl.java:457) 
at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
at java.lang.Thread.run(Thread.java:1012) 
2022-11-17 15:02:14.432 13605-16358/com.castapp D/WhisperLink: Connection - calling Connection.close for device() [device: local=false, uuid=D025D3547580E1F1A3149BDAA649352D, routes={inet=Route(ipv4:192.168.29.193, unsecurePort:36474, securePort:38380)}]
2022-11-17 15:02:14.432 13605-13605/com.castapp E/Error: Error playing video
com.connectsdk.service.command.FireTVServiceError: Error setting media source
at com.connectsdk.service.FireTVService$6.futureIsNow(FireTVService.java:613)
at com.amazon.whisperplay.fling.media.controller.impl.PlayerDeviceImpl$AsyncFutureTask.done(PlayerDeviceImpl.java:594)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
at java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
2022-11-17 15:02:14.433 13605-13605/com.castapp D/CHECK DETAILS :: {"id":"7e21ebe9-dd62-4b9c-a56b-13c4866f2ad9","lastKnownIPAddress":"D025D3547580E1F1A3149BDAA649352D","friendlyName":"naman's FireTVStick","lastConnected":1668677527,"lastDetection":1668677526,"services":{"D025D3547580E1F1A3149BDAA649352D":{"class":"FireTVService","description":{"ipAddress":"D025D3547580E1F1A3149BDAA649352D","uuid":"D025D3547580E1F1A3149BDAA649352D","friendlyName":"naman's FireTVStick","port":0,"serviceId":"FireTV"},"config":{"class":"ServiceConfig","lastDetection":1668666522,"UUID":"D025D3547580E1F1A3149BDAA649352D"}}}}
2022-11-17 15:02:16.020 13605-16282/com.castapp I/JmDNSImpl: updateRecord() name=amzn.dmgr:9E510420123173774DE800C681732F01:hRvnSWvBgf:582676 typeSubType=_amzn-wplay._tcp.local. op=Remove #listeners=2
2022-11-17 15:02:16.021 13605-16312/com.castapp D/WhisperLink: JmdnsServiceListener - Service Removed: Service Name: amzn.dmgr:9E510420123173774DE800C681732F01:hRvnSWvBgf:582676 Service Type: _amzn-wplay._tcp.local.
2022-11-17 15:02:16.021 13605-16312/com.castapp D/WhisperLink: JmdnsServiceManager - Not propagating loss of 9E510420123173774DE800C681732F01

**Comment by ubuvoid** [comment]
Thanks for the additional context. I see a Java stack trace here, which leads me to understand you're running this on Android.

Can you share what version of Android (or, if the case may be, FireOS) is running on the device these logs are from?

Thanks

**Comment by krishna4157** [comment]
Using Android 13 version.

**Comment by ubuvoid** [comment]
That's what I was thinking you'd say -- there appears to be an issue with the Android version of Whisperplay/Fling SDK that makes it so it completely breaks on recent versions of Android. I believe you are running into the same issue. I raised to my contacts at Amzn earlier this year and it appears not to have been fixed yet. (The team which previously maintained this library has seen budget cuts and I understand it's been consolidated with another organization.)

Not sure what else there is to do except escalate to Amazon via some sort of developer support. You can link to this GH issue as well as the other issue you commented on.

In the mean time, assuming you're doing this work for a commercial project, you can tell your employer it's a problem with Amazon's software. Good luck.

**Comment by krishna415741** [comment]
Thank you so much for your detailed explanation. I greatly value your support and dedication. Kudos to you 👏
